### ISSUE TITLE
mDriveOOo does not work under ArchLinux

### ISSUE THREAD

**Issue by nicolamori** [prrvchr/mDriveOOo#14]
I'm running ArchLinux and trying to make this work. I followed the guide execpet for the unistallation of the `libreoffice-sdbc-hsqldb` and `libhsqldb1.8.0-java` packages, which do not exist in ArchLinux (`hsqldb` is not installed on my system, while the former might be since Arch packages LibreOffice quite monolithically). I have been able to register the OAuth2 client using my company account (named URL) by hitting Enter but then nothing happens: I don't see any file from the online storage.

I guess ArchLinux is not supported, but since I'd really need this feature, and if there is interest in supporting Arch, I can provide feedback on request for debugging. Thanks.

**Comment by prrvchr** [comment]
Hi nicolamori,

The problem under linux whatever the edition is that the Python that I use in my extension under LibreOffice comes from the system.

Certain libraries, that I use, require binaries specific to the version of Python, the system and the architecture.

For the moment regarding Linux only the libraries for Python version 10 under x86_64 (64 bits) are delivered.
If your version of Python is other than 10, you must install the following libraries on your system with pip:

- [charset-normalizer](https://pypi.org/project/charset-normalizer/3.1.0/#files)
- [ijson](https://pypi.org/project/ijson/3.2.2/#files)
- [lxml](https://pypi.org/project/lxml/4.9.2/#files)

In addition to that, you need Java JRE version 11 minimum...

And finally under Linux it is easier to find out what is not working by launching LibreOffice (soffice) from a terminal. If errors occur, they will appear in the terminal.

**Comment by nicolamori** [comment]
I don't clearly understand what you mean with "Python 10"; maybe 3.10? Anyway Arch is a rolling release so it usually ships the latest packages (in my case python 3.11.5 and JRE 21).

I installed the packages you suggested with the package manager (not with pip) and verified from the python command line that they are available, but this did not help.

I also launched `soffice` from the command line and repeated the connection procedure. Here's the error that comes out:
```
ContentUser.__init__() Error: Traceback (most recent call last):
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/ucp/contentuser.py", line 101, in __init__
    user, root = self.Provider.getUser(source, self.Request, name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/provider.py", line 107, in getUser
    root = self._getRoot(source, request, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/provider.py", line 299, in _getRoot
    root = self._parseRoot(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/provider.py", line 333, in _parseRoot
    created = self.parseDateTime(value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/ucp/provider.py", line 274, in parseDateTime
    return getDateTimeFromString(timestamp, self.DateTimeFormat)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/dbtool/dbtool.py", line 517, in getDateTimeFromString
    now = datetime.strptime(dtstr, format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2020-04-19T01:41:30Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```
If I correctly understand it the problem is a missing decimal value in the seconds field.

**Comment by nicolamori** [comment]
I installed Python 3.10 and set up a virtualenv, then installed charset-normalizer ijson and lxml with pip. Now I get a different error:
```
ContentUser.__init__() Error: Traceback (most recent call last):
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/ucp/contentuser.py", line 90, in __init__
    self.Request = getRequest(ctx, self.Provider.Scheme, name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/oauth2/oauth2tools.py", line 48, in getRequest
    request = createService(ctx, g_service)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fp.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/unotool/unotool.py", line 340, in createService
    service = ctx.ServiceManager.createInstanceWithContext(name, ctx)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uno.com.sun.star.uno.RuntimeException: <class 'ImportError'>: No module named 'lxml.etree' (or 'plugin.extract2Json' is unknown), traceback follows
  File "/usr/lib/libreoffice/program/pythonloader.py", line 134, in activate
    mod = self.getModuleFromUrl( locationUrl )
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/libreoffice/program/pythonloader.py", line 102, in getModuleFromUrl
    exec(codeobject, mod.__dict__)
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fb.tmp_/OAuth2OOo.oxt/service/OAuth2Service.py", line 57, in <module>
    from oauth2 import getAccessToken
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fb.tmp_/OAuth2OOo.oxt/service/pythonpath/oauth2/__init__.py", line 66, in <module>
    from .plugin import extract2Json
  File "/usr/lib/libreoffice/program/uno.py", line 431, in _uno_import
    raise uno_import_exc
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fb.tmp_/OAuth2OOo.oxt/service/pythonpath/oauth2/plugin.py", line 40, in <module>
    import js2xml
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu41873c60fb.tmp_/OAuth2OOo.oxt/service/pythonpath/js2xml/__init__.py", line 1, in <module>
    import lxml.etree
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Also, an error window pops up with the message "Nonexistent object. Nonexistent file.".

**Comment by nicolamori** [comment]
Thinking that the error might come from the fact that I installed the extensions while using python 3.11 I removed them, started soffice in the virtualenv and tried to re-install the extensions. But when activating OAuth2OOo I get an error window with the following message:
```
<class 'ImportError'>: No module named 'lxml.etree' (or 'plugin.extract2Json' is unknown), traceback follows
  File "/usr/lib/libreoffice/program/pythonloader.py", line 147, in writeRegistryInfo
    mod = self.getModuleFromUrl( locationUrl )
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/libreoffice/program/pythonloader.py", line 102, in getModuleFromUrl
    exec(codeobject, mod.__dict__)
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu83949h215k.tmp_/OAuth2OOo.oxt/service/OAuth2Service.py", line 57, in <module>
    from oauth2 import getAccessToken
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu83949h215k.tmp_/OAuth2OOo.oxt/service/pythonpath/oauth2/__init__.py", line 66, in <module>
    from .plugin import extract2Json
  File "/usr/lib/libreoffice/program/uno.py", line 431, in _uno_import
    raise uno_import_exc
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu83949h215k.tmp_/OAuth2OOo.oxt/service/pythonpath/oauth2/plugin.py", line 40, in <module>
    import js2xml
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu83949h215k.tmp_/OAuth2OOo.oxt/service/pythonpath/js2xml/__init__.py", line 1, in <module>
    import lxml.etree
  File "/usr/lib/libreoffice/program/uno.py", line 352, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I didn't try to re-install the other extensions.

**Comment by prrvchr** [comment]
No this does not come from the version of python remains in 3.11.
It comes from the date returned by oneDrive which is not in the right format...

Here is the correct format:
`"createdDateTime":"2019-03-10T21:02:20.283Z","lastModifiedDateTime":"2023-09-23T14:01:10.417Z"`

This is the creation or modification date of the OneDrive drive, try with another Microsoft account.

**Comment by nicolamori** [comment]
Ok, understood. Unfortunately I don't have another account, just the one of my company. I'll see if it's possible to get a free one and try again.

**Comment by prrvchr** [comment]
Can you try with a free OneDrive account, maybe the date format is different for company accounts?

**Comment by nicolamori** [comment]
With a free account things work better. I can connect and see the documents on OneDrive, so I'd say the date format is different between business and free accounts and that it's not a bug of mDriveOOo (maybe support for business can be added?).

Anyway:
1) saving a document with LibreOffice does not seem to be reflected on the online document: opening it with Word Online I still  see the old version (but maybe it's me that don't understand how the caching mechanisms work?)
2) if I close and reopen LibreOffice I can't connect again to OneDrive because of this:
    ```
    ContentUser.__init__() Error: Traceback (most recent call last):
      File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu100573xqsu.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/ucp/contentuser.py", line 102, in __init__
        metadata = database.insertUser(user, root)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu100573xqsu.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/database.py", line 194, in insertUser
        result = call.executeQuery()
                 ^^^^^^^^^^^^^^^^^^^
    uno.com.sun.star.sdbc.SQLException: integrity constraint violation: unique constraint or index violation ; SYS_PK_10123 table: "Users"
    ```
    If I uninstall and reinstall the extensions then it works again (after registering again the OAuth2 client), but it starts again on next close and reopen.

**Comment by prrvchr** [comment]
> saving a document with LibreOffice does not seem to be reflected on the online document: opening it with Word Online I still see the old version (but maybe it's me that don't understand how the caching mechanisms work?)

It seems that if the document is opened in Word Online then it is locked and cannot be updated.
On the other hand, if Word Online is closed, the update works.

> if I close and reopen LibreOffice I can't connect again to OneDrive because of this

I just noticed this bug. It seems to happen if you have several email addresses at Microsoft, in this case you have to use the @outlook.fr or @outlook.com address, the others no longer work...

I have to think about how to solve this problem.

**Comment by nicolamori** [comment]
> It seems that if the document is opened in Word Online then it is locked and cannot be updated. On the other hand, if Word Online is closed, the update works.

What I I actually did was:
1) save with LO
2) open with WO: the modifications are visible
3) close WO
4) Re-open with LO, modify again and save
5) Re-open with WO: the new modifications are not visible
6) Save with WO and exit
7) Re-open with LO: I still see the modifications made in 4) despite 6)

> I just noticed this bug. It seems to happen if you have created an Outlook email addresses at Microsoft (@outlook.fr or @outlook.com), in this case you have to use this address, the others no longer work and if you try it, this prevent the Outlook's address from working...
> 

I resumed an old Microsoft account, one with a username which was not an email address, for doing the tests. At a certain point of the insane Microsoft identity verification chain I have been asked for my email address, then for merging the old account and the new one. Answering yes I have been told that the email was set as an alias for my old account ID. Now I can login to OneDrive either with email or old ID, and the old ID is listed in the account settings panel:

![Screenshot_20231102_082030](https://github.com/prrvchr/mDriveOOo/assets/59166070/5c5cb1a6-caff-4306-bc76-a2a75a9ec3ed)

As you see, my email address is not a Microsoft one (as far as I know I don't have an Outlook address). Furthermore, the old ID is my Skype username (still active). I don't understand if all of this actually has an impact on the bug.

> I have to think about how to solve this problem.

Thank you!

**Comment by prrvchr** [comment]
Hi nicolamori,

Normally now with the new version 1.0.7 we should be able to parse dates as provided by the Microsoft API for a business account. Since I don't have a business account, I'll let you do the testing.
Thanks in advance.

**Comment by nicolamori** [comment]
Hi @prrvchr,

I just tried version 1.07, but it's still not working. I can finish the OAuth identification correctly and I can even see my files in the `Open` window, but trying to open any of them results in an error window popping up with a message "Nonexistent object. Nonexistent file.". In the console I get this stack trace:

```
This plugin supports grabbing the mouse only for popup windows
This plugin supports grabbing the mouse only for popup windows
sdbc.BaseCallableStatement() 1: 'CALL "GetItemId"(?,?,?)'
sdb.CallableStatement() 1
Unexpected python exception with traceback: Traceback (most recent call last):
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu65866dza5h.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/contentprovider.py", line 109, in queryContent
    content = self._datasource.queryContent(self, self._authority, url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu65866dza5h.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/datasource.py", line 92, in queryContent
    itemid = user.getItemByUri(uri)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu65866dza5h.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/ucp/user.py", line 179, in getItemByUri
    itemid = self.DataBase.getItemId(self.Id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mori/.config/libreoffice/4/user/uno_packages/cache/uno_packages/lu65866dza5h.tmp_/mDriveOOo.oxt/service/pythonpath/mdrive/database.py", line 276, in getItemId
    call.execute()
uno.com.sun.star.sdbc.SQLException: query execution reached limit of recursion

qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

All of the above using python 3.11.6. With python 3.10.13 I get errors already when installing the OAuth extension, so I didn't went too far that way.

**Comment by prrvchr** [comment]
Hi nicolamori,

With version 1.0.7 the only modification is the conversion of dates which uses the Python dateutil package instead of the Python datetime package which required knowing the date format.
Although it allows you to go a little further in the connection, this modification is not sufficient and leads me to think that the Microsoft Graph APIs are not the same for OneDrive and a professional account.
And finally I can't find any documentation regarding the use of professional accounts with Microsoft APIs.
So I'm really stuck on this problem...

**Comment by nicolamori** [comment]
@prrvchr Don't worry, I can live without this feature although it could have improved my workflow. Let's hope something will show up in future that could help with this. 
Thank you very much for your efforts!

**Comment by prrvchr** [comment]
> Let's hope something will show up in future that could help with this.

In this case I will try to make the necessary modifications.

Thank you for taking the time to submit your problems, this allows me to improve the extensions.
